### ISSUE TITLE
Mod breaks cloud spawning

### ISSUE THREAD

**Issue by Mhowser** [dfgHiatus/ZipImporter#3]
When the mod is loaded, any item with cloudspawning fails,
[failed-cloud-spawn.log](https://github.com/user-attachments/files/17021829/failed-cloud-spawn.log)

here is an item to test with:
`resrec:///U-1V5GC3lNdMu/R-adf3b7ef-ac9e-41c8-931d-b5ca1396e61f`
`resdb:///d696a2aef2e35f66c74dab9cfa5ebfd0511edd8d54a504b2b7a991f9c030c410.brson`

**Comment by dfgHiatus** [comment]
Truthfully, I do not play Resonite any more and have no intention of updating things here. It does looks like the mod needs to be rebuilt to be up to date with the latest version of the game

**Comment by Mhowser** [comment]
Thanks for the update on things, if you intend to not update your mod I suggest removing it from https://github.com/resonite-modding-group/resonite-mod-manifest 

Hope you have a good day!
